### ISSUE TITLE
无法运行，三方库中的swift都报错

### ISSUE THREAD

**Issue by mrhyh** [Josin22/JSShopCartModule#1]
你打开的是.xcworkspace 文件吗?我刚下载了一个没有出错呀~

**Comment by Josin22** [comment]
你打开的是.xcworkspace 文件吗?我刚下载了一个没有出错呀~

**Comment by Josin22** [comment]
选择Pods文件,找到reactivecocoa框架 然后在setting里搜swift 看到Use Legacy Swift Language Version ==YES  ,Result框架的步骤和reactivecocoa框架一样

**Comment by Josin22** [comment]
pod 'ReactiveObjC'
