### ISSUE TITLE
单个商品删除时,商家选中状态未一起改变.

### ISSUE THREAD

**Issue by doudoudoudou** [Josin22/JSShopCartModule#5]
比如第一组组头我不选中,里面有1 2 3 4个商品,我选中 2 3 4,不选中1. 此时组头是不选中的,这没问题. 但是这时我把1删除了,此组只有2 3 4,均为选中,组头也应该变成选中状态,但是这没跟着变. 应该在删除单个cell的时候 对组头的选中状态进行遍历改变.

**Comment by Josin22** [comment]
修复了,,,现在才看到这个issues
