### ISSUE TITLE
加减号和结算的时候，如何使用RAC发起网络请求

### ISSUE THREAD

**Issue by Dtheme** [Josin22/JSShopCartModule#6]
使用一般方式发送网络请求的时候，可能由于RAC中block的原因，导致服务端接收到请求的参数为空，目前使用YTKNetwork发送请求。尝试了很久还是没有成功，请教一下该怎么做，谢谢！

**Comment by Josin22** [comment]
- (void)rowChangeQuantity:(NSInteger)quantity indexPath:(NSIndexPath *)indexPath
viewModel里你写个数量改变的请求,然后在上面那个方法里调用就行了

**Comment by Dtheme** [comment]
喔 这好像是去年提issue？那会儿已经搞定了 还是很谢谢你的回复 hhh




发自网易邮箱大师
在2017年07月22日 16:22，乔同X 写道：

Closed #6.
